### ISSUE TITLE
Any entity with glowing eyes is completely black other than the eyes.

### ISSUE THREAD

**Issue by designsbyaustin** [X0nk/Bliss-Shader#110]
Amazing shader pack! I'm absolutely loving your work. I just wanted to tell you that the shader seems to be only applying the "eyes" png texture instead of the mob texture itself. I checked the png files for my current resource pack and the "eyes" png files all have black backgrounds. 

BSL Shaders:
![Replay 2024-04-28 02-26-16 - frame at 0m38s](https://github.com/X0nk/Bliss-Shader/assets/102756861/c45970bb-e83a-43f0-8d07-63112e71f704)

Newest version of Bliss:
![Replay 2024-04-28 02-26-16 - frame at 0m9s](https://github.com/X0nk/Bliss-Shader/assets/102756861/358b0a15-5fda-4ea5-b774-2cb29e4a1149)

This happens with Endermen, Spiders, Cave Spiders, and Phantoms.
 
Thank you for your time!

**Comment by X0nk** [comment]
the default minecraft spider eyes have a fully transparent background, while alacrity does not.
(alacrity on the left, vanilla on the right)
![image](https://github.com/X0nk/Bliss-Shader/assets/122314734/914fd987-250b-460a-a1d9-48036ce1ae0d)
minecraft and other shaders just discard that part of the texture with some maths, bliss doesnt, which is why it shows up.
i can fix this, but the texture should also properly be transparent as well just to avoid further issues.

**Comment by designsbyaustin** [comment]
Thank you for the fast reply! I did fix the texture as a bandaid fix. I wonder why the shader packs don't just use transparent backgrounds instead lmao, very strange...

**Comment by hoobooh** [comment]
reviving this issue to add on that some parts of the system still require the black texture instead of transparent— namely inventory entity previews, which break and treat all transparent areas as pure white if you use actual transparent eye textures.
![image](https://github.com/X0nk/Bliss-Shader/assets/47639406/908cc2cb-57d4-4a08-9358-e4539689ae1e)

**Comment by X0nk** [comment]
i have done some trickery and made a work around that works alright...
if the vanilla emissive textures "brightness" or "luminance" falls under a specific threshold (2.55/255.0) or (0.01/1.0), it will discard the texture.
