### ISSUE TITLE
Light goes trough blocks

### ISSUE THREAD

**Issue by EQQx110** [X0nk/Bliss-Shader#111]
Sun visible trough blocks and glowing blocks seems to be related to to LabSSS, and there's also godrays going trough Distant Horizons LOD models.

![2024-04-28_23 56 39](https://github.com/X0nk/Bliss-Shader/assets/108895045/2eca1b1f-25ea-40a1-9e94-c89127b06283)
![2024-04-28_23 54 41](https://github.com/X0nk/Bliss-Shader/assets/108895045/d3fff6c6-236e-42ef-8cab-e2bae9847d6d)

**Comment by X0nk** [comment]
the godrays go through the mountain because there is no shadowmap to block it. increase the shadowmap distance.
the sunlight thing, this is screen-space shadow's subsurface scattering dying. you can either turn off subsurface scattering or turn off screenspace contact shadows in direct light -> shadows
