### ISSUE TITLE
The player reflection in the water is abnormal

### ISSUE THREAD

**Issue by wanmingleii865** [X0nk/Bliss-Shader#167]
![Uploading 2024-06-10_09.39.19.png…]()

**Comment by wanmingleii865** [comment]
![2024-06-10_09 39 19](https://github.com/X0nk/Bliss-Shader/assets/106419693/38599f39-a54d-411b-97f1-6226a48e13c1)
![2024-06-10_09 39 17](https://github.com/X0nk/Bliss-Shader/assets/106419693/cdc7dadb-da13-4fd9-a553-7f94f847df20)
![2024-06-10_09 41 45](https://github.com/X0nk/Bliss-Shader/assets/106419693/6cb0981e-60b5-44d5-bb12-8a672208b474)

**Comment by X0nk** [comment]
this is happening because the player is in the translucent render stage. the screenspace reflections intersect the world using the depth buffer that does *not* include translucent geometry. this was done so screenspace reflections worked when looking through windows. on the latest in-development version i added a setting to toggle this. 

shader settings -> misc. settings -> translucent entities.
