### ISSUE TITLE
shader broken on 1.16.5

### ISSUE THREAD

**Issue by Rasyamb** [X0nk/Bliss-Shader#22]
![IMG-20230916-WA0000](https://github.com/X0nk/Bliss-Shader/assets/124448897/b4f1df5c-3fa7-41ea-abfb-0a9c1d924061)

i have no idea what happend

**Comment by X0nk** [comment]
this is my misleading mistake.... i *thought* the shader worked all the way back to optifines 1.16.5, but it was actually 1.17... so yeah. im probably not gonna support earlier than 1.17. i will remove all things saying it supports 1.16.5.

the reason being, optifine started doing this automatic patching thing in 1.17 for openGL version specific things... turns out the shader really relies on that patcher.
