### ISSUE TITLE
Possible incompatibility with Epic Fight's Animation Shader feature

### ISSUE THREAD

**Issue by Razor235T** [X0nk/Bliss-Shader#271]
Epic Fight can eat up to 50% of fps when there are 10+ mobs around you with animations. To improve the situation, the feature Animation Shader was added, which boosts the fps in these situations. Hovewer, after turning the feature on, after about 5 mins the feature turns off and says "Failed to create shader glint. Don't turn on animation shader in your environment...". In their discord server the solution says: "Solution: You're graphic card, OS, or Shader pack is not compatible with animation shader. Do not turn on Animation Shader option in your environment." The shader doesn't turn itself off nor seem to have major bugs apart from armor being translucent while animation shader option is on.

Minecraft 1.20.1, Forge 47.3.5, Bliss's 489th commit (latest on 11.08.2024), Windows 11 23H2, Nvidia drivers 560.81 RTX 4070, Oculus 1.7.0, Epic Fight 20.8.9. I have lots of mods installed, including Distant Horizons.

![image](https://github.com/user-attachments/assets/133d9472-0fc1-473c-936f-0f1e5ee5ac48)
![2024-08-11_22 54 26](https://github.com/user-attachments/assets/4f966e5c-f1ce-44d9-8bf1-46cfbbebf674)
[latest.log](https://github.com/user-attachments/files/16575947/latest.log)

**Comment by X0nk** [comment]
custom shaders from a mod often dont play nice with iris shaders.

for the other issue, im pretty sure the armor being weird is an unrelated problem, caused by shoulder surfing.

there's 2 ways to work around it:
- A: change the shoulder surfing mod config parameter `adjust_player_transparency` and set it to false
- B: turn off `TRANSLUCENT_ENTITIES` in `shader settings -> debug/experimental`

option A will make the camera kinda annoying in tight spaces.
option B will make all entities that were once see-through, completely opaque, and no longer see-through.

**Comment by Razor235T** [comment]
That's a Leawind's Third Person mod, which is not bugging without Epic Fight's Shader Animation feature. I have translucent thing turned off in their config, though. Will try turning off Translucent Entities, too. Shame shader animation turns off by itself, I hope they'll fix it :(
