### ISSUE TITLE
Intel End Support

### ISSUE THREAD

**Issue by ShrikerChestTree** [X0nk/Bliss-Shader#29]
# When going into The End on the new version, I have this happening
![2023-10-13_23 51 36](https://github.com/X0nk/Bliss-Shader/assets/107254774/37e82305-7832-4346-8aeb-355e7ff0cf88)
Please fix this in the next version

**Comment by X0nk** [comment]
i cannot fix it with the little information you have provided.
iris should have given you information to copy from the game chat when the error happened, please send me that.

**Comment by ShrikerChestTree** [comment]
> i cannot fix it with the little information you have provided.
> iris should have given you information to copy from the game chat when the error happened, please send me that.

Here is the error:
composite2.fsh: composite2.fsh: ERROR: 0:370: 'waterVolumetrics_notoverworld' : no suitable overloaded function found (implicit conversion used) 
ERROR: 0:370: 'waterVolumetrics_notoverworld' : no known function

**Comment by X0nk** [comment]
Could you try the latest commit i just pushed? if it still errors, please send the error information.

on a side not, the latest commits are not very gameplay friendly, because as i said on your other issue about physics mod, i just did an internal rework, so alot of stuff is in a currently unfinished, not gamplay friendly state. the end, most of all, is not finished yet.

**Comment by ShrikerChestTree** [comment]
> Could you try the latest commit i just pushed? if it still errors, please send the error information.

I tried it and it fixed everything! Thanks!
