### ISSUE TITLE
Wobbly effect around character with TAA on?

### ISSUE THREAD

**Issue by ZenobiaCatnap** [X0nk/Bliss-Shader#344]
So, with TAA on, my character in third person gets this jitter effect around them, and only when they're moving. I know this is caused by TAA, as it doesn't happen with it off. But I would quite like to keep TAA on, so...

Is there anyway to keep TAA, without the jitter around your character when you're moving?

https://github.com/user-attachments/assets/ccec4406-b2e9-4276-b2fc-0b7d6a0bcb57

**Comment by X0nk** [comment]
this is caused by TAA itself. iris does not provide movement information from any entities, so the TAA cannot interact with that motion in the best possible way. there is nothing you can do in the settings but reduce blend factor so it happens *a little bit less*

heres an example of what i mean by "best possible way"
this image has 2 armor stands, they are not moving in a way that isnt relevant to the movement of the camera, so they can be taken into account in motion. the player however, is not moving relative to the camera, and moves completely independently. 

you can see the difference between having motion data and no motion data lol 
![image](https://github.com/user-attachments/assets/c2ec9b3e-7440-4e9e-ad1f-0532a2c8d93b)

one day in the future, iris developers will implement entity motion vectors. once that happens, i can get that motion data.
