### ISSUE TITLE
Incompatibility with Hysteria shaders

### ISSUE THREAD

**Issue by Firro007** [X0nk/Bliss-Shader#376]
I want to ask if there is a way how to fix this or if its just incompatible. Game crashes in a minute when i pull out any blicky out of tacz mod.

forge v. 47.3.22
Hysteria shaders v. 1.0.0
minecraft v. 1.20.1
tacz v. 1.0.3

**Comment by X0nk** [comment]
what? hysteria shaders (the photon edit?)??? bliss is a whole different shader from that. they are not related in any way.

also, TACZ has a memory leak coming from a conflict with iris that they havent fixed yet apparently, since you are still crashing
[i talked a little more about it in this issue here](https://github.com/X0nk/Bliss-Shader/issues/308)
