### ISSUE TITLE
Visible drowned's heads deep down in water from the surface

### ISSUE THREAD

**Issue by Patomosm** [X0nk/Bliss-Shader#378]
### Describe the bug
When you are in the air you can see the head of a drowned mob that is deep down in the water, like a dark cube.
See the image below.

### Describe how your minecraft is set up
1. NOTE: Minecraft is loading random mob's head from Mojang, like christmas chests.
![Base Profile Screenshot 2024 12 28 - 17 18 02 64](https://github.com/user-attachments/assets/69c70177-dc16-464a-9457-deaa2b282930)

3. If you cannot do option 1. Please list the following information instead:
- What GPU: RTX 4070
- What operating system: Windows 11 Pro 24H2
- What minecraft version: 1.21.1
- If you are using a special client: No
- What shader loading mod you are using: Iris 1.8.0 beta3
- What version of the shader you are using: Bliss Commit #482
- If you are using any, what additional mods you are using besides the ones required to use the shader: Distant Horizon, JourneyMap

### Describe how to reproduce the bug
I don't know, I just realize it while I was in creative mode flying over a river. I'm in singleplayer mode using SomethingTrue_Overworld texture pack (https://legacy.curseforge.com/members/patomosm/projects).

**Comment by X0nk** [comment]
This is normal, as extremely unfortunate as it is.
it is a limitation of how bliss is designed when it composites its different effects together.

to be more technical, bliss is a "hybrid forward/deferred renderer", specifically, the opaque terrain is deferred rendered, and translucent things are forward rendered. some entities are rendered as a translucent thing (like piglins, players, some mob heads)

translucent things are composited onto the image *after* water fog has been rendered. this is done so the water fog is *behind* the water surface (a translucent thing). unfortunately the water fog is always behind the translucent things, no matter their relative positions. even if the fog is right at your eyes, translucent surfaces will be fully visible at all times. 

there's no simple fix for this, sadly. which is why it still happens. i will erase it from existence the moment a viable way comes up lol i hate it so much
