### ISSUE TITLE
Feature request: add more anti-alias like fxaa or msaa

### ISSUE THREAD

**Issue by OutsiderH** [X0nk/Bliss-Shader#41]

**Comment by X0nk** [comment]
due to technical limitations, MSAA cant be implemented.
FXAA can, but i dont really personally like FXAA.

the final and largest reason is, this shader heavily relies on the re-projection aspect of TAA to reduce noise, so i can use less sampels for alot of shader effects, which is a key part in getting the high performance. the shader will be a horrid noisy mess without TAA as-is. so unless you like stacking FXAA + pretty aggressive TAA, i dont see much sense in it.
