### ISSUE TITLE
Incorrect rendering of connected textures (under water)

### ISSUE THREAD

**Issue by gladtroll** [X0nk/Bliss-Shader#6]
1.19.3 fabric (quilt) using iris 1.5.2

![image](https://github.com/X0nk/Bliss-Shader/assets/20322238/4d2e69cc-43d2-452f-a2c5-916151c910a1)

as well the junctions of blocks (with connected textures), move in waves:

![image](https://github.com/X0nk/Bliss-Shader/assets/20322238/e66b50b7-e528-4253-9a4a-68b186581bf5)

**Comment by X0nk** [comment]
This happens because the CTM is using the translucent render layer, and is treated differently than opaque stuff.
you can see it through the water fog because the water fog when seen from outside the water is _always_ rendered before the pass that puts transparent things in.
when you go underwater, a different water fog is rendered _after_ the transparent pass, so it is always in front of transparent things.
i cannot do much about this issue without essentially restructuring the shader, which is a whole task in itself that i wont be doing.
