### ISSUE TITLE
Bright glow from enchanted items

### ISSUE THREAD

**Issue by TheLastPringle0** [X0nk/Bliss-Shader#75]
Enchanted items give off an extremely bright glow
This effect is less prominent during the day, but becomes overwhelmingly bright at night
![image](https://github.com/X0nk/Bliss-Shader/assets/123025180/6a8cb121-1bed-47ec-b2fc-b1566a1ec6f1)
![image](https://github.com/X0nk/Bliss-Shader/assets/123025180/9e8045f4-2140-4187-9145-56449eafc49d)

**Comment by X0nk** [comment]
could i have more information please?
do you have any additional mods besides the ones needed to use the shader?
what hardware are you using?
have you changed any settings?

**Comment by TheLastPringle0** [comment]
I am using the shader with default settings and have disabled every mod except fabric api, sodium and iris
screenshot should hopefully contain any relevant hardware info
![image](https://github.com/X0nk/Bliss-Shader/assets/123025180/c68f321c-b039-4bca-9196-498cb876c356)

**Comment by TheLastPringle0** [comment]
I should probably also add that I am running arch linux, if it could in any way be causing it
Reopened the issue as I closed it by accident

**Comment by icheered** [comment]
I have the exact same issue, I'm on Fedora Linux, also using AMD GPU

**Comment by X0nk** [comment]
im pretty sure its not related to your drivers, but im working to fix it. enchanted items are just kinda dead right now

**Comment by xenanthropy** [comment]
Note:
It's still WAY too bright, but i've noticed that turning off `handheld light` makes enchanted weapons a lot less blinding! Unfortunately you lose handheld torches because of this, but you could always install a mod that adds dynamic light, I suppose...
![2024-04-03_10 36 26](https://github.com/X0nk/Bliss-Shader/assets/3527107/7c4c83a2-7c1b-4170-8f8b-f15df07e51fc)
![2024-04-03_10 36 52](https://github.com/X0nk/Bliss-Shader/assets/3527107/974a6b5a-d8b2-4a95-9807-8604278f452e)

**Comment by Macintosh-Fan** [comment]
Me too, but with a modded block:
<img width="514" alt="image" src="https://github.com/X0nk/Bliss-Shader/assets/50642934/956c0537-7223-4510-92bf-db3239ba70a4">

Though, probably just an issue with some glowing blocks.

**Comment by X0nk** [comment]
these issues probably do not exist anymore on the latest in-development versions. would be nice to know for sure though
