### ISSUE TITLE
1.20.1 Bliss breaks banners with gradient pattern

### ISSUE THREAD

**Issue by AutofillMe** [X0nk/Bliss-Shader#96]
With Iris and Bliss, if a banner has the gradient pattern applied (up or down) it removes all applied banner patterns.

Notice my hotbar renders the item model correctly with the gradient applied, but when placed it has no pattern.
![2024-04-07_23 06 06](https://github.com/X0nk/Bliss-Shader/assets/113013764/b4cf5520-567d-4e55-87da-6764319b7e4d)

**Comment by X0nk** [comment]
i fixed this on the latest in-development version by using iris's translucent entities programs.

**Comment by fr1g** [comment]
here the gradient banner broken again but a bit different, don't know if it's the shader's issue but after i disabled the shader it went normal

- game version: 1.21.5
- iris: 1.8.11
- sodium: 0.6.13

![Image](https://github.com/user-attachments/assets/96488eeb-0a01-49c8-a388-bee2bd0cf9dd)

btw the complementary-unbound also a bit weird. not finished the gradient smoothly, though it's gradient is working:

![Image](https://github.com/user-attachments/assets/b47ffe6a-6ec0-488c-9264-16b6129cf8ab)

I suppose this issue should be reopened.

**Comment by X0nk** [comment]
the feature iris provides to shaders that use deferred rendering, the [separate entity draws feature](https://shaders.properties/current/reference/shadersproperties/ordering/#separateentitydraws)
Bliss is a hybrid forward/deferred renderer (translucent things are forward rendered, opaque things are deferred rendered)
so it makes use of this feature from iris to properly render entities that have translucent parts that need to be blended to some degree. this includes banners

this is where the problem comes in... Iris accidentally broke this feature for banners in 1.21.4+
if you test in 1.21.3 or older you'll see that the banner works fine with the same shader, unchanged. i have tested this personally, and told the iris developer about it.

as to why complementary works fine, it doesnt use that iris feature due to being completely forward rendered.
